Added missing #include <stdexcept>
Building on Arch Linux failed, throwing a `error: ‘runtime_error’ is not a member of ‘std’` error for both system_warning.cpp and falling_text.cpp due too a missing include (stdexcept).
I added the include statement for the library which should resolve this.